### ISSUE TITLE
v::cnpj()->validate('00.000.000/0000-00') returning true

### ISSUE THREAD

**Issue by souzace** [Meroje/laravel-respect#1]
HI, you can fix it issue, to return false, please.

**Comment by jody-frankowski** [comment]
Can you fix this please @Meroje .
Thank you so much :)

**Comment by Yimiprod** [comment]
@Meroje i think you should fix this issue. It's been there for more almost two years.
Thanks a lot.

**Comment by jody-frankowski** [comment]
What is taking you so long :( ?

**Comment by simstefani** [comment]
Plz i need it NOW

**Comment by Yimiprod** [comment]
Do it ! JUST ... DO IT !!
![DO IT](https://media.giphy.com/media/3o85xtLX7zCyeeWGLC/giphy.gif)
